// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchedulingService.Data;

#nullable disable

namespace SchedulingService.Migrations
{
    [DbContext(typeof(SchedulingDbContext))]
    [Migration("20260315134728_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchedulingService.Models.InterviewSlots", b =>
                {
                    b.Property<long>("InterviewSlotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InterviewSlotID"));

                    b.Property<int>("InterviewType")
                        .HasColumnType("int");

                    b.Property<long>("JobID")
                        .HasColumnType("bigint");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SlotStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeStart")
                        .HasColumnType("datetime2");

                    b.HasKey("InterviewSlotID");

                    b.ToTable("InterviewSlots", (string)null);
                });

            modelBuilder.Entity("SchedulingService.Models.ScheduledInterview", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("InterviewSlotID")
                        .HasColumnType("bigint");

                    b.Property<int>("InterviewStatus")
                        .HasColumnType("int");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InterviewSlotID");

                    b.HasIndex("StudentId");

                    b.ToTable("ScheduledInterview", (string)null);
                });

            modelBuilder.Entity("SchedulingService.Models.StudentAvailability", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReasonStatus")
                        .HasColumnType("int");

                    b.Property<string>("ReasonStudent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentAvailability", (string)null);
                });

            modelBuilder.Entity("SchedulingService.Models.ScheduledInterview", b =>
                {
                    b.HasOne("SchedulingService.Models.InterviewSlots", "InterviewSlot")
                        .WithMany()
                        .HasForeignKey("InterviewSlotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterviewSlot");
                });
#pragma warning restore 612, 618
        }
    }
}
